### ISSUE TITLE
Restrict access to resources based on permissions, not roles on frontend Vue.js App

### ISSUE THREAD

**Issue by sekafi** [creativetimofficial/ct-vue-material-dashboard-laravel-pro#12]
# Version

The current latest version

# Current Behavior

In the Vue.js frontend application only user roles are supported and permissions are not available.
Permissions are available only in backend laravel app. 

It is also a pity that in "Role management" it is not possible to view or edit the permissions assigned to the selected role.

#  Expected Behavior

If the logged in user belongs to some role that has certain permissions, how can I get the logged in user's permissions list so that I can restrict access to resources based on permissions, not roles? Should MeConttroller be changed?

**Comment by teamupdivision** [comment]
Hi @sekafi,

Thanks for reporting this and for using Creative Tim products.

Unfortunately, the product was built to work with 3 types of roles (admin, creator, and member) and the associated default permissions in the backend. We didn’t create it to work with frontend permissions so we’re afraid this would require an extended and different type of work.

If you think there is another way we can help or if you need more info, please let us know. 

Best,
UPDIVISION Team

**Comment by teamupdivision** [comment]
Hi @sekafi,
 
Hope this helped in clarifying the issue. We will go ahead and close this ticket. If there is anything else that can be fixed or we can help with, please let us know.

Best,
UPDIVISION Team

P.S. If you need help with any of your projects, we're happy to get in touch. We do custom development for start-ups and companies across the globe (you can check out our portfolio here https://updivision.com/portfolio and some happy clients over here https://updivision.com/testimonials). Don`t hesitate to drop us a line at office@updivision.com or by using our contact form (https://updivision.com/contact).
