### ISSUE TITLE
Problem with product - Error 401

### ISSUE THREAD

**Issue by Zahroon** [creativetimofficial/ct-vue-material-dashboard-laravel-pro#13]
https://vue-material-dashboard-laravel-pro.creative-tim.com/examples/user-profile

There is a problem in the console with the whole product.

**Comment by teamupdivision** [comment]
Hi there @Zahroon, 

Thank you for the update on this issue and for using Creative Tim products.
Please let us know if you have any other problems or if you need any other specific info. 

Best,
UPDIVISION Team

P.S. If you need help with any of your projects, we're happy to get in touch. We do custom development for start-ups and companies across the globe (you can check out our portfolio here https://updivision.com/portfolio and some happy clients over here https://updivision.com/testimonials). Don`t hesitate to drop us a line at office@updivision.com or by using our contact form (https://updivision.com/contact).
