### ISSUE TITLE
Image upload failing

### ISSUE THREAD

**Issue by OV-Hank** [creativetimofficial/ct-vue-material-dashboard-laravel-pro#14]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

I expect the image upload from the profile to be saved and the file location to be updated to mysql server.

# Current Behavior

The file gets moved to the storage/app/users folder but then fails.

# Failure Information (for bugs)

screenshot attached

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. navigate to user profile
2. click select image
3. select image for import
4. click update profile

## Context

running on mamp locally.

* Device: macbook pro
* Operating System: Big Sur 11.5.2
* Browser and Version: chrome 101.0.4951.64

## Failure Logs
from networking
<img width="835" alt="Screen Shot 2022-06-03 at 3 10 28 PM" src="https://user-images.githubusercontent.com/104928196/171944138-e94bdd03-e285-4b02-a405-5c3ffea7f8ff.png">
<img width="904" alt="Screen Shot 2022-06-03 at 3 10 53 PM" src="https://user-images.githubusercontent.com/104928196/171944145-7182792b-b3a0-4c27-8677-16ee55315fc7.png">
<img width="561" alt="Screen Shot 2022-06-03 at 3 11 22 PM" src="https://user-images.githubusercontent.com/104928196/171944150-0444f10b-ec9a-49ae-b3a7-8b7178289922.png">

{
    "errors": [
        {
            "status": "422",
            "title": "Unprocessable Entity",
            "detail": "The profile image format is invalid.",
            "source": {
                "pointer": "/data/attributes/profile_image"
            },
            "meta": {
                "failed": {
                    "rule": "url"
                }
            }
        }
    ]
}

**Comment by teamupdivision** [comment]
Hi @OV-Hank,

Thank you for using the Creative Tim products!

It seems like you don't generate the correct URL path for the image.
In the config > filesystems, you need to add `'url' => env('APP_URL').'/storage',` for the disks array, local.

If you have any other questions, please let us know.

Best,
UPDIVISION Team

**Comment by OV-Hank** [comment]
Thanks, that seemed to do the trick.

I do have another question that I haven't been able to find an answer for after googling the last couple of days.

The items table has a user_id field.  I want to make the item list page only display the items that belong to the logged in user.   Where/how would I add this parameter?  I've searched but the way this app is setup isn't like any of the many tutorials, stackoverflow posts I have come across.  

For example on the below snapshot, user with ID 4 is logged in, he should only be able to see the last item that belongs to him and not the first 3 that belong to user with ID 1.

Thanks so much for your help!

<img width="1129" alt="Screen Shot 2022-06-10 at 9 30 01 AM" src="https://user-images.githubusercontent.com/104928196/173088150-edd22006-deac-4333-8b50-b049e73f3d40.png">

**Comment by teamupdivision** [comment]
Hi @OV-Hank,

There are multiple possibilities for your request:

1. You can send the id of the logged user in the backend and take directly from there the associated items.
2. You can filter the items depending on the logged user in the list function from items-service.js.
3. You can create restrictions depending on what you want to show in Item policy, in the view function.

**Comment by teamupdivision** [comment]
Hi @OV-Hank,

We hope we managed to help you in solving this issue.

Should you need further assistance, do not hesitate to let us know.

Best,
UPDIVISION Team
