### ISSUE TITLE
Abandoned Packages

### ISSUE THREAD

**Issue by krebbi** [creativetimofficial/ct-vue-material-dashboard-laravel-pro#2]
When installing the API I get the following Notices:

Package moontoast/math is abandoned, you should avoid using it. Use brick/math instead.
Package spatie/laravel-cors is abandoned, you should avoid using it. Use laravel/framework instead.
Package jakub-onderka/php-console-color is abandoned, you should avoid using it. Use php-parallel-lint/php-console-color instead.
Package jakub-onderka/php-console-highlighter is abandoned, you should avoid using it. Use php-parallel-lint/php-console-highlighter instead.

**Comment by teamupdivision** [comment]
Hi @krebbi,

Sorry for the late response. 
The problem that you encounter will be solved once we upgrade the theme to Laravel 8, we plan to do this in the next 1-2 weeks. 
Will get back to you with a confirmation once it is done.

Best,

UPDIVISION

**Comment by jorgev121** [comment]
Any news with the update? I still waiting to use Laravel 8

**Comment by teamupdivision** [comment]
Hello, sorry for the delays.
We'll take care of it this month.
I will follow up when done

**Comment by teamupdivision** [comment]
Hi @jorgev121 @krebbi 
The API product was updated to Laravel 8.
You can download it from the downloads section in the Creative Tim website.
Let me know if everything's OK.

All the best, and thanks for your patience
