### ISSUE TITLE
Theme issue with Sidebar Mini 

### ISSUE THREAD

**Issue by krebbi** [creativetimofficial/ct-vue-material-dashboard-laravel-pro#3]
The Content isn't expanding to the left when minifying the Sidebar.
In the Free Version it works like expected.

![Bildschirmfoto 2020-11-03 um 14 42 10](https://user-images.githubusercontent.com/3884521/97992312-ce8b9280-1de2-11eb-93e1-824ba3b90743.png)
![Bildschirmfoto 2020-11-03 um 14 41 45](https://user-images.githubusercontent.com/3884521/97992319-d0555600-1de2-11eb-9d8f-0e55a4c74e02.png)

**Comment by krebbi** [comment]
Line 671 in /src/assets/scss/md/_sidebar-and-main-panel.scss should be

'width: $sidebar-mini-width;'


Line 33 in /src/assets/scss/md/_misc.scss should be removed.

**Comment by teamupdivision** [comment]
Hi there,

We are glad that you were able to solve the problem. 
We also incorporated the changes that you suggested!

Thank you,

UPDIVISION

P.S. If you need help with any of your projects, we're happy to get in touch. We do custom development for start-ups and companies across the globe (you can check out our portfolio here https://updivision.com/portfolio and some happy clients over here https://updivision.com/testimonials). Don`t hesitate to drop us a line at office@updivision.com or by using our contact form (https://updivision.com/contact).
