### ISSUE TITLE
Laravel version framework

### ISSUE THREAD

**Issue by YaangVu** [creativetimofficial/ct-vue-material-dashboard-laravel-pro#5]
When I run 'composer install' , I got the bellow issue:

> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

In PackageManifest.php line 131:

  Undefined index: name

Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

**Comment by teamupdivision** [comment]
Hello, @YaangVu!
Thanks for using our products.
We'll follow up soonest with an answer to your issues.
All the best

**Comment by teamupdivision** [comment]
Please let us know what PHP version you are using.
Thank you

**Comment by YaangVu** [comment]
@teamupdivision I use php version 7.2.34

**Comment by teamupdivision** [comment]
Hello @YaangVu,

It's most probably a composer version problem.
You need to either update or downgrade your composer, please check this link:
https://jianjye.com/articles/30/how-to-fix-undefined-index-name-in-packagemanifestphp-line-131-error-with-composer

You should also remove the vendor folder and package-lock.json file after upgrading/downgrading composer.

If you have anymore issues please reopen the ticket.

All the best
