### ISSUE TITLE
api/v1/login request status remains "Pending""

### ISSUE THREAD

**Issue by polinevol** [creativetimofficial/ct-vue-material-dashboard-laravel-pro#6]
# Prerequisitles

- [ x] I am running the latest version
- [ x] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed
- [ x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

After the installation, when trying to login with defaults users, it don't works
# Current Behavior

The login request status remains "Pending"

## Steps to Reproduce

On New fresh installation according to documentation

## Context

* Device: PC HP Probook PHP 7.4 MySQL 8
* Operating System: Windows 10
* Browser and Version: lastest  Google chrome

**Comment by teamupdivision** [comment]
Hello, this issue is being solved over email support, thank you
