### ISSUE TITLE
Auto Complete - example with API

### ISSUE THREAD

**Issue by ezawadzki** [creativetimofficial/ct-vue-material-dashboard-laravel-pro#8]
Hi,

Is it possible to provide an example of auto-complete linked to Laravel API using JSONAPI best practice ?

There is already an implementation of auto-complete but only with static data :
`/src/pages/Dashboard/Layout/TopNavbar.vue`

Thanks,

Emilie

**Comment by teamupdivision** [comment]
Hi Emilie, @ezawadzki 

Thank you for sending this and for using Creative Tim products. 

The easiest would be to use a custom component, like the one below. 

https://vuejsexamples.com/a-vue-component-for-a-simple-searchable-dropdown/

Please let us know if you need any other info or if there is anything else we can help with.

Best,
UPDIVISION Team

**Comment by teamupdivision** [comment]
Hi Emilie, @ezawadzki 
 
Hope this helped. We will go ahead and close this ticket. If there is anything else that can be fixed or we can help with, please let us know.

Best,
UPDIVISION Team

P.S. If you need help with any of your projects, we're happy to get in touch. We do custom development for start-ups and companies across the globe (you can check out our portfolio here https://updivision.com/portfolio and some happy clients over here https://updivision.com/testimonials). Don`t hesitate to drop us a line at office@updivision.com or by using our contact form (https://updivision.com/contact).
