### ISSUE TITLE
Avatars are not visible. Links to avatars refer to wrong address

### ISSUE THREAD

**Issue by sekafi** [creativetimofficial/ct-vue-material-dashboard-laravel-pro#9]
# Version

The current latest version downloaded a few days ago

# Current Behavior

Avatars are not visible in the VUE frontend application. 

Links to avatars refer to the VUE address (eg. http://vue.lan/images/admin.jpg). 

![vue_lan_avatars_not_visible](https://user-images.githubusercontent.com/67909670/130919372-63c54a8b-e50c-4a3b-9ee0-ec77a7c31c8e.png)

#  Expected Behavior

Links to avatars should refer to LARAVEL app (eg. http://laravel.lan/images/admin.jpg). 

JSON from Laravel API: 
```
{
    "data": {
        "type": "users",
        "id": "1",
        "attributes": {
            "name": "Admin",
            "email": "admin@jsonapi.com",
            "profile_image": "/images/admin.jpg",
      (...)
}
```

Maybe the API should pass the full link to the avatar ? How can I change it?

# Context

* Device: PC
* Operating System: Windows 10
* Browser and Version: Chrome 92.0.4515.159

**Comment by teamupdivision** [comment]
Hi @sekafi,

Here are a few details on this. It looks like the error is caused by the following:

APP_URL variable from api .env file should contain the URL of your Laravel JSON: API Project (eg. http://laravel-json-api-v2.test). The error means that the path is not correct.

Please let us know if this helped.
 
Best,
UPDIVISION Team

**Comment by sekafi** [comment]
Thank you. It helped.

**Comment by teamupdivision** [comment]
Thank you very much for the update @sekafi. We're very glad. If there is anything else we can help with, please let us know.

Best,
UPDIVISION Team

P.S. If you need help with any of your projects, we're happy to get in touch. We do custom development for start-ups and companies across the globe (you can check out our portfolio here https://updivision.com/portfolio and some happy clients over here https://updivision.com/testimonials). Don`t hesitate to drop us a line at office@updivision.com or by using our contact form (https://updivision.com/contact).
